name: Testing Secret

on:
  workflow_dispatch:

jobs:
  test_secret:
    runs-on: uubtu-latest
    steps:
      - name: Hello world action
        run: echo "Hi Secret! ${{ secrets.NANDO_SECRET }}"    
